### ISSUE TITLE
Smithery Configuuration

### ISSUE THREAD

**Issue by benborla** [benborla/mcp-server-mysql#11]
Hi @calclavia, need your advice on my smithery.yaml, I followed the structure from https://smithery.ai/docs/config#smitheryyaml but it doesn't seem to be working.

I'm just seeing this on the Installation section

![Image](https://github.com/user-attachments/assets/e20fd181-1158-4106-b512-f5cabff25bc5)

Deployment seems to be fine.

![Image](https://github.com/user-attachments/assets/b470a08c-f8b7-44af-88b4-b5b7c16809a4)

Here's the config I added
```yaml
# Smithery configuration file: https://smithery.ai/docs/config#smitheryyaml

startCommand:
  type: stdio
  configSchema:
    # JSON Schema defining the configuration options for the MCP.
    type: object
    required:
      - mysqlHost
      - mysqlPort
      - mysqlUser
    properties:
      mysqlHost:
        type: string
        description: The host address of the MySQL database.
      mysqlPort:
        type: string
        description: The port number for connecting to MySQL.
      mysqlUser:
        type: string
        description: The username for MySQL authentication.
      mysqlPass:
        type: string
        description: The password for the specified MySQL user.
      mysqlDb:
        type: string
        description: The database name to connect to. If left blank, retrieves all
          databases.
      ssl:
        type: boolean
        default: false
        description: If set to true, the connection will use SSL.
      rejectUnauthorizedSSL:
        type: boolean
        default: false
        description: If set to true, the connection will verify the SSL certificate.
      allowInsertOperation:
        type: boolean
        default: false
        description: If set to true, INSERT operations will be allowed.
      allowUpdateOperation:
        type: boolean
        default: false
        description: If set to true, UPDATE operations will be allowed.
      allowDeleteOperation:
        type: boolean
        default: false
        description: If set to true, DELETE operations will be allowed.
    commandFunction:
      |-
      (config) => ({
        "command": "node",
        "args": [
          "dist/index.js"
        ],
        "env": {
          "MYSQL_HOST": config.mysqlHost,
          "MYSQL_PORT": config.mysqlPort,
          "MYSQL_USER": config.mysqlUser,
          "MYSQL_PASS": config.mysqlPass,
          "MYSQL_DB": config.mysqlDb, 
          "MYSQL_SSL": config.ssl, 
          "MYSQL_SSL_REJECT_UNAUTHORIZED": config.rejectUnauthorizedSSL,
          "ALLOW_INSERT_OPERATION": config.allowInsertOperation,
          "ALLOW_UPDATE_OPERATION": config.allowUpdateOperation,
          "ALLOW_DELETE_OPERATION": config.allowDeleteOperation
        }
      })

```
